<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sale Report Print</title>
    <link rel="stylesheet" href="{{ asset('css/madura-mart.css') }}">
</head>
<body class="print-report-body" onload="window.print()">

    <div class="no-print print-no-print-controls">
        <button onclick="window.print()">Print Report</button>
        <button onclick="window.close()">Close</button>
    </div>

    <div class="print-header">
        <h2>Madura Mart Management</h2>
        <p>Jalan Raya Telang No. 123, Bangkalan, Madura</p>
        <p>Sales Report</p>
    </div>

    <div class="print-meta">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d F Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d F Y') }} <br>
        <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }} <br>
        <strong>Date Generated:</strong> {{ date('d F Y H:i') }}
    </div>

    <table class="print-table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="15%">Date</th>
                <th width="20%">Receipt No</th>
                <th width="30%">Cashier</th>
                <th width="30%" class="text-right">Total Amount (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $index => $sale)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $sale->sale_date->format('d/m/Y') }}</td>
                    <td>TRX-{{ str_pad($sale->id, 5, '0', STR_PAD_LEFT) }}</td>
                    <td>{{ $sale->user->name ?? '-' }}</td>
                    <td class="text-right">{{ number_format($sale->total_price, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="print-total-row">
                <td colspan="4" class="text-right">GRAND TOTAL REVENUE</td>
                <td class="text-right">Rp {{ number_format($totalRevenue, 0, ',', '.') }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="print-signature">
        <p>Bangakalan, {{ date('d F Y') }}</p>
        <br><br><br>
        <p>( Manager )</p>
    </div>

</body>
</html>