<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Report Print</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h2 { margin: 0; text-transform: uppercase; }
        .header p { margin: 5px 0; color: #555; }
        .meta { margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .table th { background-color: #f2f2f2; text-transform: uppercase; font-size: 10px; }
        .text-right { text-align: right; }
        .total-row td { font-weight: bold; background-color: #eee; }
        @media print {
            @page { margin: 1cm; size: A4; }
            .no-print { display: none; }
        }
    </style>
</head>
<body onload="window.print()">

    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()">Print Report</button>
        <button onclick="window.close()">Close</button>
    </div>

    <div class="header">
        <h2>Madura Mart Management</h2>
        <p>Jalan Raya Telang No. 123, Bangkalan, Madura</p>
        <p>Purchase Report</p>
    </div>

    <div class="meta">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d F Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d F Y') }} <br>
        <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }} <br>
        <strong>Date Generated:</strong> {{ date('d F Y H:i') }}
    </div>

    <table class="table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="12%">Date</th>
                <th width="18%">Note Number</th>
                <th width="25%">Distributor</th>
                <th width="10%" class="text-right">Items</th>
                <th width="30%" class="text-right">Total Amount (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purchases as $index => $purchase)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $purchase->purchase_date->format('d/m/Y') }}</td>
                    <td>{{ $purchase->note_number }}</td>
                    <td>{{ $purchase->distributor->name ?? 'General / No Distributor' }}</td>
                    <td class="text-right">{{ $purchase->details->sum('purchase_amount') }}</td>
                    <td class="text-right">{{ number_format($purchase->total_price, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="5" class="text-right">GRAND TOTAL EXPENDITURE</td>
                <td class="text-right">Rp {{ number_format($totalExpenditure, 0, ',', '.') }}</td>
            </tr>
        </tfoot>
    </table>

    <div style="margin-top: 30px; text-align: right;">
        <p>Bangkalan, {{ date('d F Y') }}</p>
        <br><br><br>
        <p>( Manager )</p>
    </div>

</body>
</html>
