<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Report Print</title>
    <link rel="stylesheet" href="{{ asset('css/madura-mart.css') }}">
</head>
<body class="print-report-body" onload="window.print()">

    <div class="no-print print-no-print-controls">
        <button onclick="window.print()">Print Report</button>
        <button onclick="window.close()">Close</button>
    </div>

    <div class="print-header">
        <h2>Madura Mart Management</h2>
        <p>Jalan Raya Telang No. 123, Bangkalan, Madura</p>
        <p>Purchase Report</p>
    </div>

    <div class="print-meta">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d F Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('d F Y') }} <br>
        <strong>Generated By:</strong> {{ Auth::user()->name ?? 'System' }} <br>
        <strong>Date Generated:</strong> {{ date('d F Y H:i') }}
    </div>

    <table class="print-table">
        <thead>
            <tr>
                <th width="5%">No</th>
                <th width="12%">Date</th>
                <th width="18%">Note Number</th>
                <th width="25%">Distributor</th>
                <th width="10%" class="text-right">Items</th>
                <th width="30%" class="text-right">Total Amount (Rp)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($purchases as $index => $purchase)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $purchase->purchase_date->format('d/m/Y') }}</td>
                    <td>{{ $purchase->note_number }}</td>
                    <td>{{ $purchase->distributor->name ?? 'General / No Distributor' }}</td>
                    <td class="text-right">{{ $purchase->details->sum('purchase_amount') }}</td>
                    <td class="text-right">{{ number_format($purchase->total_price, 0, ',', '.') }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="print-total-row">
                <td colspan="5" class="text-right">GRAND TOTAL EXPENDITURE</td>
                <td class="text-right">Rp {{ number_format($totalExpenditure, 0, ',', '.') }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="print-signature">
        <p>Bangkalan, {{ date('d F Y') }}</p>
        <br><br><br>
        <p>( Manager )</p>
    </div>

</body>
</html>
